#!/usr/bin/env bash
# setup-agent-skills.sh — .agents/skills/ を正本として各 AI ツール向けにセットアップ
#
# 対応ツール:
#   Claude Code : .claude/skills/<name> → ../../.agents/skills/<name> (symlink)
#   GitHub Copilot : .github/copilot-instructions.md (自動生成)
#   Codex : グローバル管理のためプロジェクト内設定不要 (スキップ)
#
# 使い方: bash scripts/setup-agent-skills.sh
# 冪等: 何度実行しても同じ結果

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
AGENTS_DIR="${REPO_ROOT}/.agents/skills"

if [ ! -d "$AGENTS_DIR" ]; then
  echo "No .agents/skills/ directory found. Nothing to do."
  exit 0
fi

# --- Claude Code: symlink .claude/skills/<name> → ../../.agents/skills/<name> ---

CLAUDE_SKILLS_DIR="${REPO_ROOT}/.claude/skills"
mkdir -p "$CLAUDE_SKILLS_DIR"

for skill_dir in "$AGENTS_DIR"/*/; do
  [ -d "$skill_dir" ] || continue
  skill_name="$(basename "$skill_dir")"
  link_path="${CLAUDE_SKILLS_DIR}/${skill_name}"
  target="../../.agents/skills/${skill_name}"

  if [ -L "$link_path" ]; then
    current_target="$(readlink "$link_path")"
    if [ "$current_target" = "$target" ]; then
      echo "  Claude Code: ${skill_name} (up to date)"
      continue
    fi
    rm "$link_path"
  elif [ -e "$link_path" ]; then
    echo "  Claude Code: ${skill_name} — skipped (not a symlink)"
    continue
  fi

  ln -s "$target" "$link_path"
  echo "  Claude Code: ${skill_name} -> ${target}"
done

# --- GitHub Copilot: generate .github/copilot-instructions.md ---

GITHUB_DIR="${REPO_ROOT}/.github"
COPILOT_FILE="${GITHUB_DIR}/copilot-instructions.md"
mkdir -p "$GITHUB_DIR"

{
  echo "<!-- Auto-generated by scripts/setup-agent-skills.sh. Do not edit manually. -->"
  echo "# Copilot Instructions (Refloom)"
  echo ""
  echo 'Follow `AGENTS.md` strictly.'
  echo ""
  echo "Before writing code, read:"
  echo "1. \`AGENTS.md\` — project conventions, build/test commands"
  echo "2. \`ARCHITECTURE.md\` — system architecture"
  echo "3. \`docs/adr/\` — architecture decision records"
  echo ""

  # List skills
  echo "## Project Skills"
  echo ""
  for skill_dir in "$AGENTS_DIR"/*/; do
    [ -d "$skill_dir" ] || continue
    skill_name="$(basename "$skill_dir")"
    skill_file="${skill_dir}/SKILL.md"

    # Extract description from frontmatter
    desc=""
    if [ -f "$skill_file" ]; then
      desc="$(sed -n 's/^description: *//p' "$skill_file" | head -1)"
    fi

    if [ -n "$desc" ]; then
      echo "- **${skill_name}**: ${desc}"
    else
      echo "- **${skill_name}**"
    fi
  done
  echo ""
  echo "## Hard Rules"
  echo ""
  echo "- All changes require PR to main (no direct push)"
  echo "- \`make ci\` must pass before merge"
  echo "- Use \`feature/*\` or \`fix/*\` branch naming"
  echo "- Check ADRs before changing architecture decisions"
} > "$COPILOT_FILE"

echo "  Copilot: copilot-instructions.md generated"

# --- Codex: skip (global management via ~/.agents/skills/) ---
echo "  Codex: skipped (global management)"

echo "Done."
